### ISSUE TITLE
Overview broker requires instance name when updating a service instance

### ISSUE THREAD

**Issue by ablease** [mattmcneeney/overview-broker#12]
OSBAPI says, only the [service instance guid](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#body-6) is required. 

Overview broker rejects requests from cf to update a service instance. 

```
→ cf update-service my-db -p complex
Updating service instance my-db as admin...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker rejected the request to http://overview-broker.grove-flier.sapi.cf-app.com/v2/service_instances/d2cf0174-a1cd-4a2f-b96c-be3e94df4f3a?accepts_incomplete=true. Status Code: 400 Bad Request, Body: instance requires property "name"
```

**Comment by mattmcneeney** [comment]
Aha! The `name` field is a configuration parameter that the `complex` plan requires. If you take a look at the schema, you can see that it is a required field!
