### ISSUE TITLE
Keep hosted overview-broker up to date. 

### ISSUE THREAD

**Issue by ablease** [mattmcneeney/overview-broker#16]
Hey matt

Is the hosted overview-broker at the-best-broker.cfapps.io always kept up to date with the latest commit?

If not we should fix that ;)

**Comment by mattmcneeney** [comment]
Unfortunately, it's not. It's deployed on PWS and so I'm not sure how I can set up a concourse pipeline to do this given I have to login with SSO.

**Comment by mattmcneeney** [comment]
This is now fixed! 👏
