### ISSUE TITLE
Overview-Broker remote image?

### ISSUE THREAD

**Issue by NickyMateev** [mattmcneeney/overview-broker#17]
Hi,

I was wondering if you intend on uploading a docker image of the **overview-broker** somewhere - maybe on **DockerHub** or **Quay**?

This would greatly simplify the spinning up of a overview-broker deployment without having to clone/fork your repository.

If you don't have this planned, is it okay for others to upload their own images in personal container repositories?

**Comment by mattmcneeney** [comment]
Thanks for the suggestion @NickyMateev. I've just added a CI job to automatically build and push the latest overview-broker to Dockerhub!

You can find it here: https://hub.docker.com/r/mattmcneeney/overview-broker

Hope that helps!

**Comment by NickyMateev** [comment]
@mattmcneeney Thanks for the quick response and reaction! This will surely help. 👍

**Comment by mattmcneeney** [comment]
Hey @NickyMateev 
Just a quick note to let you know that the Dockerhub image has moved to `ismteam/overview-broker`.

**Comment by oleg-yudovich** [comment]
Hey @mattmcneeney 
Any chance to add arm64 support for the Apple M1?

**Comment by mattmcneeney** [comment]
Sorry @oleg-yudovich I no longer work on this and won't have the time to do this. cc @Samze in case he knows of anyone still working in this space!
