### ISSUE TITLE
Node modules vendoring?

### ISSUE THREAD

**Issue by deniseyu** [mattmcneeney/overview-broker#6]
`cf push` logs out this warning:

```
         PRO TIP: It is recommended to vendor the application's Node.js dependencies
         Visit http://docs.cloudfoundry.org/buildpacks/node/index.html#vendoring
```

**Comment by mattmcneeney** [comment]
Yeah, I think you just need to run `npm install` before doing a `cf push`, so that the local copy of the `node_modules` are uploaded rather than the buildpack downloading the packages itself. (I think)
